### ISSUE TITLE
Merge fix branches 

### ISSUE THREAD

**Issue by EulalieCoevoet** [SofaDefrost/SoftRobots#11]
Hi @margaretkoehler, @VannesteFelix 

You share some changes in these branches:  
* fixVSCompilation
* fix_missing-dll-link

I feel like they are good fix and we should merge them into master (and delete them after?). Is it a work in progress? What do you think?

**Comment by margaretkoehler** [comment]
Yeah, that would be great to merge those changes into the master. I am working on a different branch (StiffnessControl) that comes off of fixVSCompilation. Would deleting fixVSCompilation cause problems for the other branch?

**Comment by EulalieCoevoet** [comment]
@margaretkoehler no it should be fine.
Thanks you both I will merge the changes.
