### ISSUE TITLE
SOFA (v22.04) crashes when opening Tripod tutorial (Sofapython3/tutorials/Tripod) from SOFA/file/load file

### ISSUE THREAD

**Issue by camilla-agabiti** [SofaDefrost/SoftRobots#136]
Hi everyone, I have installed the SOFA version 22.04 on Linux. I noticed that SOFA crashes when opening a scene directly from SOFA (file/open).
I attach the log file so that you can take a look at it and verify that all the needed plugins and libraries were loaded.
[sofa_crash.log](https://github.com/SofaDefrost/SoftRobots/files/8538838/sofa_crash.log)

Instead, if the same scene is opened by writing the file path as argument in the command windows it works. @hugtalbot @damienmarchal @fredroy

**Comment by damienmarchal** [comment]
Thank @camilla-agabiti  for reporting, we have our coding session today so we will investigate that....
