### ISSUE TITLE
Connect with Solidworks model

### ISSUE THREAD

**Issue by ozilxu** [SofaDefrost/SoftRobots#148]
Hi， @alxbilger @guparan may I ask how I can import my Solidworks file into the sofa?

**Comment by alxbilger** [comment]
@ozilxu I don't know about the file formats that Solidworks can export. Most of the mesh loaders are in this folder: https://github.com/sofa-framework/sofa/tree/master/Sofa/Component/IO/Mesh/src/sofa/component/io/mesh. You can check if one of the loaders is compatible with your file.

**Comment by ozilxu** [comment]
> @ozilxu I don't know about the file formats that Solidworks can export. Most of the mesh loaders are in this folder: https://github.com/sofa-framework/sofa/tree/master/Sofa/Component/IO/Mesh/src/sofa/component/io/mesh. You can check if one of the loaders is compatible with your file.

Thanks for the help! I will try with this mesh loader!
