### ISSUE TITLE
Having trouble opening step 4 of Tripod Tutorial

### ISSUE THREAD

**Issue by Cuberkk** [SofaDefrost/SoftRobots#226]
Hi guys,

When I am trying to open Step 4-1 of Tripod Tutorial, there will be a warning in the terminal:
[Terminal](https://drive.google.com/file/d/1G-UVD2a00pxYrE82PJG_G3dvem79Z7IZ/view?usp=drive_link)
and showing nothing in SOFA.([SOFA_interface](https://drive.google.com/file/d/1xu_Dt74KtsHRi-omHhM9_DqhOq_OYbBN/view?usp=drive_link))
After I added these plugins into the plugin-list, the warning disappeared while there was still nothing shown in SOFA.
(The same thing happens to Step 4-2 & Step 4-3 files)
Anyone have any ideas about how to fix this?

**Comment by alxbilger** [comment]
Hi,

could you host your files directly in this conversation? They are currently not shared on gdrive, and if you delete them, people won't be able to understand your question.

Also, tell us how you use SOFA (binaries or compiled from sources?), and the versions of SOFA and SoftRobots. Thanks.

**Comment by Cuberkk** [comment]
Hi,

Sorry for the delay responding and confusion.

I am using a SOFA binaries (V22.12.00) on the Windows. And I just use the SoftRobots plugins in the plugin_files of the V22.12.00 SOFA binaries.

So when I run the Step 4-1, what appears in my SOFA interface is:
![Tripod4_1](https://github.com/SofaDefrost/SoftRobots/assets/134013590/14868913-9437-435f-9bfd-091bfda6cd1b)
and what appears in the terminal is:
![Tripod4_1_Terminal](https://github.com/SofaDefrost/SoftRobots/assets/134013590/c5033d19-ce74-4d6e-bd75-52eaf3b134c2)
Do you have any ideas what might go wrong?

**Comment by alxbilger** [comment]
The log in the terminal does not bring any information on the actual problem. Do you have any other error message before what you shared?

Can you check in the `View` tab in the interface that something is checked (Force Fields for example)?

Where did you get the scene file. Is this a scene shared with the SOFA binaries or did you get them from GitHub?

**Comment by alxbilger** [comment]
The scenes in the `myproject` folder are for you to write (your are in a tutorial). If you want the final scene, go in the `details` folder.

**Comment by Cuberkk** [comment]
Got it!
I got it work on my computer. There are some warning on the terminal while the scene can be animated.
![image](https://github.com/SofaDefrost/SoftRobots/assets/134013590/baff1274-afbb-485b-bbe1-2b3a344cd5fd)

**Comment by alxbilger** [comment]
If you get the latest version of the scene on GitHub, the error should go away.

**Comment by Cuberkk** [comment]
Got it. Thanks!
