### ISSUE TITLE
update, doUpdate & writing Engines

### ISSUE THREAD

**Issue by damienmarchal** [SofaDefrost/SoftRobots#23]
Hi,

I looked into the engines  implemented in the SoftRobots plugins and they probably are not correct. 

The good news is that recently there was changes in sofa on how to/should engines be implemented to make that easier to detect and harder to make invalid code. The changes are breaking but this is a good opportunity to fix that in our plugins. And the doc has been updated:
https://www.sofa-framework.org/community/doc/programming-with-sofa/start-coding/create-your-engine/

The fix is here: https://github.com/SofaDefrost/SoftRobots/pull/24

EDIT: As usual when I see repeated patterns in all source files, this always rings a bell I wonder...is this thing really useful ?  
```
  virtual std::string getTemplateName() const
    {
        return templateName(this);
    }

    static std::string templateName(const VolumeFromTriangles<DataTypes>* = nullptr)
    {
        return DataTypes::Name();
    }
```

**Comment by EulalieCoevoet** [comment]
The bug has been fixed in PR#24.

The remain issue is with `getTemplateName()`.
