### ISSUE TITLE
Wrong behavior in the workshop tutorial 

### ISSUE THREAD

**Issue by damienmarchal** [SofaDefrost/SoftRobots#44]
During the workshop it was noticed that the Cable based finger react in a weird way to the CTRL+ and -.

Test: 
file:///home/dmarchal/Bureau/PREPARE/SOFA_v19.06.99_custom_Linux_v5.1/plugins/SoftRobots/docs/tutorials/CableGripper/details/step4.pyscn

**Comment by EulalieCoevoet** [comment]
What is weird exactly? I just tested it and everything seems fine to me.

**Comment by damienmarchal** [comment]
So it was fixed.
