### ISSUE TITLE
Build error duing installation

### ISSUE THREAD

**Issue by CLiu-eng** [SofaDefrost/SoftRobots#50]
Hi,

I tried to use source code to install SOFA and SoftRobots plugin on Mac OS 10.15.4.
I got the unstable version of SOFA by `git clone -b master https://github.com/sofa-framework/sofa.git sofa/master/src/`

I also got one version from `git clone https://github.com/SofaDefrost/SoftRobots`, but when I configured it in CMake GUI, it always reported the error as below.
![Screenshot 2020-04-26 at 16 49 20](https://user-images.githubusercontent.com/57107556/80312637-0d121600-87de-11ea-8b17-22dde6ac750d.png)

Then I download the Plugin SoftRobots 17.12 version instead. The 17.12 version of SoftRobot configured well then I generated the whole file.

However, when I tried to build it and after a long wait, it reports errors as below. The screenshot is not complete but other errors are similar to these.
![image](https://user-images.githubusercontent.com/57107556/80292764-e528a100-8750-11ea-9c52-5b298c0475a8.png)

It seems that there's something wrong with the softrobots plugin in the source code. I am not sure what caused this problem. Is it because the versions of SOFA and SoftRobots Plugin are not compatible? Has anyone met this before? How can I solve this problem? 

Thank you!

**Comment by EulalieCoevoet** [comment]
Hi CLiu-eng,

Sorry no one helped you yet. Did you manage to fix the problem? 
I think for building problems it is better to ask on Sofa forum. There are already SoftRobots related topics there.

**Comment by CLiu-eng** [comment]
Thank you for following up with my question and it has been sorted.

________________________________

**Comment by EulalieCoevoet** [comment]
Okay great.
