### ISSUE TITLE
Build error : cannot find -lSofaCommon

### ISSUE THREAD

**Issue by AlexThuthu** [SofaDefrost/SoftRobots#53]
Hello, I'm trying to install SoftRobots but I can't get pass this error :
`/usr/bin/ld: cannot find -lSofaCommon
collect2: error: ld returned 1 exit status
external_directories/SoftRobots/tests/CMakeFiles/SoftRobots_test.dir/build.make:328: recipe for target 'bin/SoftRobots_test' failed
make[2]: *** [bin/SoftRobots_test] Error 1
CMakeFiles/Makefile2:12297: recipe for target 'external_directories/SoftRobots/tests/CMakeFiles/SoftRobots_test.dir/all' failed
make[1]: *** [external_directories/SoftRobots/tests/CMakeFiles/SoftRobots_test.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2`

I did try to use SOFA/SoftRobots from your binaries and it works, so I guess something's wrong with the way I'm building it ?

**Comment by EulalieCoevoet** [comment]
Hi,
Sorry for the late reply. Did you manage to fix the problem?
I think for building problems it is better to ask/look at Sofa forum.
