### ISSUE TITLE
First steps tuto : 'js: Uncaught SyntaxError: Unexpected end of input'

### ISSUE THREAD

**Issue by akruszew** [SofaDefrost/SoftRobots#59]
When clicking : `Change the color of the cube, directly in the code` : console says `js: Uncaught SyntaxError: Unexpected end of input` and nothing else happens.

**Comment by damienmarchal** [comment]
Thank for reporting @akruszew 
Given that new version of Sofa+SoftRobots are now available I close the issue. Please report if this still happens with new version.
