### ISSUE TITLE
SofaPython 3 in V20.12 binaries

### ISSUE THREAD

**Issue by akruszew** [SofaDefrost/SoftRobots#77]
missing shared lib libpython3.7m.so.1.0

**Comment by EulalieCoevoet** [comment]
Hello Alex,

It means that you should install python3.7 or forgot to install numpy (see required dependencies [here](https://github.com/sofa-framework/sofa/releases)).
A good test is to run python3.7 in your terminal and try `import numpy`, you should not get any errors.
